### ISSUE TITLE
悠船AI可以free一下吗？

### ISSUE THREAD

**Issue by DigitalNomad-Chat** [LLM-Red-Team/free-api-hub#6]
国产Midjourney生图AI悠船 https://desktop.youchuan.cn/
这个可以free一下吗？

**Comment by Vinlic** [comment]
https://github.com/LLM-Red-Team/jimeng-free-api
建议试一下即梦每天66次，悠船的次数太少不够用

**Comment by DigitalNomad-Chat** [comment]
> https://github.com/LLM-Red-Team/jimeng-free-api 建议试一下即梦每天66次，悠船的次数太少不够用

即梦和悠船我都试过了哈，一些类型的图片，悠船生成的更加美观，比如logo，插画这些
